/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as ReferencesRouteImport } from './routes/references'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanSlugRouteImport } from './routes/plan.$slug'

const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferencesRoute = ReferencesRouteImport.update({
  id: '/references',
  path: '/references',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanSlugRoute = PlanSlugRouteImport.update({
  id: '/plan/$slug',
  path: '/plan/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plans': typeof PlansRoute
  '/progress': typeof ProgressRoute
  '/references': typeof ReferencesRoute
  '/roadmaps': typeof RoadmapsRoute
  '/plan/$slug': typeof PlanSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plans': typeof PlansRoute
  '/progress': typeof ProgressRoute
  '/references': typeof ReferencesRoute
  '/roadmaps': typeof RoadmapsRoute
  '/plan/$slug': typeof PlanSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plans': typeof PlansRoute
  '/progress': typeof ProgressRoute
  '/references': typeof ReferencesRoute
  '/roadmaps': typeof RoadmapsRoute
  '/plan/$slug': typeof PlanSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plans'
    | '/progress'
    | '/references'
    | '/roadmaps'
    | '/plan/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plans' | '/progress' | '/references' | '/roadmaps' | '/plan/$slug'
  id:
    | '__root__'
    | '/'
    | '/plans'
    | '/progress'
    | '/references'
    | '/roadmaps'
    | '/plan/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlansRoute: typeof PlansRoute
  ProgressRoute: typeof ProgressRoute
  ReferencesRoute: typeof ReferencesRoute
  RoadmapsRoute: typeof RoadmapsRoute
  PlanSlugRoute: typeof PlanSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/references': {
      id: '/references'
      path: '/references'
      fullPath: '/references'
      preLoaderRoute: typeof ReferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$slug': {
      id: '/plan/$slug'
      path: '/plan/$slug'
      fullPath: '/plan/$slug'
      preLoaderRoute: typeof PlanSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlansRoute: PlansRoute,
  ProgressRoute: ProgressRoute,
  ReferencesRoute: ReferencesRoute,
  RoadmapsRoute: RoadmapsRoute,
  PlanSlugRoute: PlanSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
